# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 18:12
from __future__ import unicode_literals

import django.core.files.storage
from django.db import migrations, models
import sifilesmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('sifilesmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sifile',
            name='filename',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Seafile\\Py\\si\\data'), upload_to=sifilesmanager.models.upload_to_sha1),
        ),
    ]
