# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-04 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniziative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniziativa',
            name='iva_scaricabile',
            field=models.BooleanField(db_index=True, default=True, verbose_name='In Uso'),
        ),
    ]
