# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 14:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TabellaStatoOrdini',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('azienda', models.CharField(default='ASC', max_length=10)),
                ('anno', models.CharField(default='2016/2017', max_length=10)),
                ('protocollo', models.CharField(blank=True, max_length=6, validators=[django.core.validators.MinLengthValidator(3)], verbose_name="Numero di protocollo dell'ordine se presente")),
                ('contratto', models.CharField(blank=True, max_length=80, verbose_name='Riferimento al contratto con il fornitore, se presente.')),
                ('data', models.DateField(verbose_name="Data dell'ordine")),
                ('competenza', models.CharField(max_length=10, verbose_name="Mese di competenza dell'ordine, nel caso di più mesi devo inserire più righe")),
                ('stato', models.IntegerField(choices=[(1, 'Bozza'), (2, 'Emettere'), (3, 'Firmato'), (4, 'Spedito')], default=1)),
                ('fornitore', models.CharField(max_length=80, verbose_name='Nome del fornitore')),
                ('tipo', models.IntegerField(choices=[(1, 'Acquisto'), (2, 'Abbonamento')], default=1)),
                ('descrizione', models.CharField(max_length=120, verbose_name="Descrizione dell'ordine")),
                ('iniziativa', models.CharField(max_length=80, verbose_name='Iniziativa/e di riferimento')),
                ('imponibile', models.IntegerField(verbose_name="Imponibile dell'ordine")),
                ('iva_presente', models.BooleanField(default=True, verbose_name="Mi dice se l'IVA è presente")),
                ('iva_detraibile', models.IntegerField(verbose_name='Percentuale di IVA detraibile')),
                ('totale_costo', models.IntegerField(verbose_name="Costo totale dell'ordine comprensivo di IVA indetraibile")),
                ('pagamento', models.CharField(max_length=80, verbose_name="scadenza di pagamento dell'ordine")),
                ('fatture_protocolli', models.CharField(max_length=80, verbose_name='Numero/i di protocollo delle fatture')),
                ('note', models.CharField(max_length=1000, verbose_name="Eventuali note sull'ordine")),
                ('in_uso', models.BooleanField(db_index=True, default=True, verbose_name="L'ordine è valido ?")),
                ('data_aggiornamento', models.DateTimeField(auto_now=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Ordini',
                'verbose_name': 'Ordine',
            },
        ),
    ]
