# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 15:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siprof', '0003_auto_20170408_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permissions',
            new_name='Profile',
        ),
    ]
